### ISSUE TITLE
Update kernel-ci-backend default branch name

### ISSUE THREAD

**Issue by alee-ccu** [kernelci/kernelci-backend-config#32]
Just found the the script fails at:
```
TASK [install-app : Checkout kernel-ci-backend code] ***************************
fatal: [kernelci]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force master", "msg": "Failed to checkout master", "rc": 1, "stderr": "error: pathspec 'master' did not match any file(s) known to git\n", "stderr_lines": ["error: pathspec 'master' did not match any file(s) known to git"], "stdout": "", "stdout_lines": []}
    to retry, use: --limit @/tmp/kernelci-backend-config/site.retry
And I checked the branch became main in /srv/kernelci/ on the VM.
```

Due to the default branch is `main` indeed in
   https://github.com/kernelci/kernelci-backend/branches

We should update the default branch name for ansible playbook.

**Comment by gctucker** [comment]
I thought GitHub would redirect things like that, but yes it needs to be updated in any case.  Ideally we should have a way to keep testing the Ansible playbook and deploy the code continuously with it, but that's a bit more work.

**Comment by alee-ccu** [comment]
@gctucker I prepared a PR for this:
 https://github.com/kernelci/kernelci-backend-config/pull/33

**Comment by alee-ccu** [comment]
Close this issue as RP has been merged:
 https://github.com/kernelci/kernelci-backend-config/pull/33
